# Generated by Django 4.2.30 on 2026-09-24 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="ticket",
            name="updated_at",
        ),
    ]
